import styles from "./index.module.css";
import { type NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Knock Knock</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.container}>
          <div className={styles.headlineContainer}>
            <h1 className={styles.h1}>
              Knock Knock ✊🚪
            </h1>
            <h2 className={styles.h2}>
              Who&#39;s There Tomorrow?
            </h2>
          </div>
          <div className={styles.buttonContainer}>
            <button className={styles.button}>I&#39;ll be there 🙌</button>
            <button className={styles.button}>I&#39;ll be home 🛋</button>
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
